That's me!
chssigma/cool-repo pull request #31
Opened 2018-09-14 18:53 UTC by AhmedAl-Doori

2018-09-19 15:18 UTC, Tim-Jackins commented
Check out this [link](https://chris.beams.io/posts/git-commit/) and let me know when you do. Then I'll merge your changes.

2018-09-19 15:21 UTC, Tim-Jackins requested changes
Let me know when you've read the comment.

2018-09-24 18:40 UTC, AhmedAl-Doori commented
Yes I got it
Summary is not to do what I did

2018-09-25 15:23 UTC, Tim-Jackins approved these changes

2018-09-25 15:23 UTC, merged